### PR TITLE
Added individual modmail, and modmail mention to my_messages

### PR DESCRIPTION
**Pull request by nekosune**
lets redd access modmail when the user has access.

### CODE REVIEW

**Comment by avidw** [comment]
Awesome, I really appreciate the PR. Do you mind moving the method to `Redd::Objects::Subreddit` and using `display_name` of the `Subreddit` object instead of the first argument?

**Comment by nekosune** [comment]
Not at all! Do you want the commit to be squashed or okay with a second commit?

**Comment by avidw** [comment]
I'm fine with a second commit. If you add another commit to that branch, the pull request should automatically update.

**Comment by avidw** [comment]
Actually, the request would basically cancel the pull request, so could you undo that commit and create a new PR? If it's too much trouble, I can do it myself.

**Pull request closed without merging**
